/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Servicios.ServiciosUsuarios;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import ws.gamesnetworksoap.server.ConnectionException_Exception;
import ws.gamesnetworksoap.server.InternalErrorException_Exception;
import ws.gamesnetworksoap.server.UnauthorizedException_Exception; 
import ws.gamesnetworksoap.server.Usermodel; 

/**
 *
 * @author Alejandro Suárez
 */
public class AdministrarUsuario extends javax.swing.JDialog {

    private Ventana ventana;
    private Usermodel usermodel;

    public AdministrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    AdministrarUsuario(Ventana parent, boolean modal, Usermodel aux) throws UnauthorizedException_Exception {
        super(parent, modal);
        ventana = parent;
        usermodel = aux;
        
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        this.setLocation(x, y);
        try {
            pintarUserModel(usermodel);
        } catch (InternalErrorException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error interno",
                        JOptionPane.WARNING_MESSAGE);
        } 
    }

    private void pintarUserModel(Usermodel usermodel) throws InternalErrorException_Exception, UnauthorizedException_Exception  {
        titulo.setText(titulo.getText()+" "+usermodel.getId());
        Identificador.setText(Integer.toString(usermodel.getId()));
        Username.setText(usermodel.getUsername()!= null ?usermodel.getUsername():"");
        Nombre.setText(usermodel.getNombre()!= null ?usermodel.getNombre():"");
        Edad.setText(usermodel.getEdad() != null ? Integer.toString(usermodel.getEdad()) : "");
        Email.setText(usermodel.getEmail()!= null ?usermodel.getEmail():"");
        Localizacion.setText(usermodel.getLocalization()!= null ?usermodel.getLocalization():"");
        Boolean cierto = ServiciosUsuarios.isAuthenticated(ventana.getTokenUsuario());
        Autenticado.setText(String.valueOf(cierto));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Identificador = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Localizacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Autenticado = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Identificador");

        jLabel2.setText("Username");

        jLabel3.setText("Nombre");

        jLabel5.setText("Email");

        jLabel6.setText("Edad");

        Identificador.setEditable(false);

        Edad.setEditable(false);

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Localizacion.setEditable(false);

        jLabel7.setText("Localizacion");

        jButton2.setText("Eliminar usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Esta autenticado?");

        Autenticado.setEditable(false);
        Autenticado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutenticadoActionPerformed(evt);
            }
        });

        jButton4.setText("Refrescar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titulo.setText("Administrar usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username)
                            .addComponent(Nombre)
                            .addComponent(Email)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Autenticado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Autenticado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    public void refrescarUsuario() {
        try {
            usermodel = ServiciosUsuarios.getUser(usermodel, ventana.getTokenUsuario());
            this.pintarUserModel(usermodel);
        } catch (InternalErrorException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error interno",
                        JOptionPane.WARNING_MESSAGE);
        } catch (UnauthorizedException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "No autorizado",
                        JOptionPane.WARNING_MESSAGE);
        } catch (ConnectionException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error de conexion",
                        JOptionPane.WARNING_MESSAGE);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            int i = JOptionPane.showConfirmDialog(this,
                    "Esta usted seguro de que quiere eliminar el usuario " + usermodel.getNombre() + "?",
                    "Eliminar usuario: " + usermodel.getNombre(),
                    JOptionPane.OK_CANCEL_OPTION);
            if (i == 0) {
                ServiciosUsuarios.deleteUser(usermodel, ventana.getTokenUsuario());
                pintarUserModel(usermodel);
                ventana.obtenerUsuarios();
                this.dispose();
            }
        }  catch (InternalErrorException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error interno",
                        JOptionPane.WARNING_MESSAGE);
        } catch (UnauthorizedException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "No autorizado",
                        JOptionPane.WARNING_MESSAGE);
        } catch (ConnectionException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error de conexion",
                        JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        refrescarUsuario();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Integer id = Integer.parseInt(Identificador.getText());
        String username = Username.getText();
        String nombre = Nombre.getText();
        String email = Email.getText();
        if (id != null
                && username != null
                && !username.isEmpty()
                && nombre != null && !nombre.isEmpty()
                && email != null && !email.isEmpty()) {
            usermodel.setUsername(username);
            usermodel.setId(id);
            usermodel.setNombre(nombre);
            usermodel.setEmail(email);
            try {
                int updateUser = ServiciosUsuarios.updateUser(usermodel, ventana.getTokenUsuario());
                if (updateUser == 1) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario ha sido actualizado con exito",
                            "Actualizado",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Error actualizando el usuario seleccionado",
                            "Error de actualizado",
                            JOptionPane.WARNING_MESSAGE);
                }
            } catch (InternalErrorException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error interno",
                        JOptionPane.WARNING_MESSAGE);
        } catch (UnauthorizedException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "No autorizado",
                        JOptionPane.WARNING_MESSAGE);
        } catch (ConnectionException_Exception ex) {
           JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error de conexion",
                        JOptionPane.WARNING_MESSAGE);
        }

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se han introducido correctamente los datos por lo que no se ha actualizado",
                    "Error en los datos",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void AutenticadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutenticadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutenticadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministrarUsuario dialog = new AdministrarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Autenticado;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Identificador;
    private javax.swing.JTextField Localizacion;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
